title: Study Abroad
description: >-
  Study Abroad Blog<br>
  with Hina.
url: "https://whitesky.kr/"
baseurl: "auslife/"
github: scottjsh
email: scottjsh@whitesky.kr
google_analytics: "G-8Y61NXMVLR"

exclude: [README.md, Gemfile, Gemfile.lock]

sass:
  sass_dir: ./assets/css

comments:
  enabled: true
  repo: "scottjsh/auslife"
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
